### ISSUE TITLE
Partial search is not working

### ISSUE THREAD

**Issue by rleitan** [mozilla-iam/dino-park-search#13]
[Steps to reproduce]:
1.Open https://dinopark.mozilla.community/org
2.Select the search box and search for a term e.g. Nic

[Expected result]:
All contacts which contain the searched term should be displayed

[Actual result]:
0 results

**Comment by fiji-flo** [comment]
Fixed by #10 
Deployed to dev-preview. Deployment to staging is pending.

http://dinopark.mozilla.community/beta/s/London vs http://dinopark.mozilla.community/beta/s/Lon
